#!/usr/bin/env bash

if [ ! -d "/var/www/html/laravel-crm" ]; then
  composer create-project krayin/laravel-crm
  chmod 777 /var/www/html/laravel-crm/storage
  chmod 777 /var/www/html/laravel-crm/storage/logs
  chmod 666 /var/www/html/laravel-crm/storage/logs/laravel.log
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ];then
    exec gosu $WWWUSER "$@"
else
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
